### ISSUE TITLE
Warning on font-family

### ISSUE THREAD

**Issue by pdclark** [stylesplugin/styles#42]
``` css
#searchsubmit,.styles .post-password-required input[type="submit"],#respond input#submit{background-image:none}body .site{padding-left:0;
padding-right:0;
max-width:74.285714285rem}#masthead,#main,#colophon{padding-left:2.857142857rem;
padding-right:2.857142857rem}html,body.styles{background-color:#5a6f96}.styles #page{background-color:#fff;
font-size:14px;

font-family:<br /> <b>Warning</b>: Illegal offset type in isset or empty in <b>/home/isafec5/public_html/gotami.net/wp-includes/pomo/translations.php</b> on line <b>72</b><br /> 

{"family":"Arial, Helvetica, sans-serif", "name":"Arial";
color:#160a05}.styles #page #masthead{background-color:#97adbf}.styles #page .site-title,.styles #page .site-title a{font-size:36px}.styles #page .site-title a{color:#efefef!important}.styles .nav-menu{background-color:#e1ecf7}.styles .main-navigation ul.nav-menu,.styles .main-navigation div.nav-menu > ul{border-color:#663316}.styles #page .main-navigation li a{font-size:16px;
color:#406cb7}.styles #page .main-navigation li a:hover{color:#ad6a27}.styles #page .main-navigation ul ul a{font-size:16px}
```
